In [45]:
import numpy as np 
import pandas as pd 

In [46]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1


In [47]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [48]:

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [49]:

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [50]:

clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [51]:

y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [52]:

from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9016393442622951
Accuracy of Decision Trees 0.7868852459016393


In [53]:

confusion_matrix(y_test,y_pred1)

array([[26,  6],
       [ 0, 29]])

In [54]:
confusion_matrix(y_test,y_pred2) 

array([[22, 10],
       [ 3, 26]])

In [55]:
print("precision of lr",precision_score(y_test,y_pred1,average=None))
print("recall of lr",recall_score(y_test,y_pred1))
print("f1_score of lr",f1_score(y_test,y_pred1))

precision of lr [1.         0.82857143]
recall of lr 1.0
f1_score of lr 0.90625


In [56]:
# for decission tree
print("precision of dt",precision_score(y_test,y_pred2))
print("recall of dt",recall_score(y_test,y_pred2))
print("f1_score of dt",f1_score(y_test,y_pred2))

precision of dt 0.7222222222222222
recall of dt 0.896551724137931
f1_score of dt 0.8


In [33]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

# As a dataframe
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [35]:

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [36]:

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [37]:

clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [38]:

y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [39]:

from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9666666666666667
Accuracy of Decision Trees 0.9333333333333333


In [40]:
confusion_matrix(y_test,y_pred1)

array([[14,  0,  0],
       [ 0,  7,  1],
       [ 0,  0,  8]])

In [41]:
confusion_matrix(y_test,y_pred2) 

array([[14,  0,  0],
       [ 0,  7,  1],
       [ 0,  1,  7]])

In [62]:
print("precision of lr",precision_score(y_test,y_pred1,average='micro'))
print("recall of lr",recall_score(y_test,y_pred1))
print("f1_score of lr",f1_score(y_test,y_pred1))

precision of lr 0.9016393442622951
recall of lr 1.0
f1_score of lr 0.90625


In [63]:
# for decission tree
print("precision of dt",precision_score(y_test,y_pred2))
print("recall of dt",recall_score(y_test,y_pred2))
print("f1_score of dt",f1_score(y_test,y_pred2))

precision of dt 0.7222222222222222
recall of dt 0.896551724137931
f1_score of dt 0.8
